language: node_js

node_js:
  - "node"

env:
  - CODECOV_TOKEN="30165a72-a5bd-46fc-94fe-ec430871a2ea"

install:
  - npm install -g codecov

script:
  - npm test
  - instanbul cover ./node_modules/lab/bin/lab --report lcovonly -- -l && codecov
